src/Entity/Commune.php
<?php

namespace App\Entity;

use App\Repository\CommuneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommuneRepository::class)]
class Commune
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_commune = null;

    #[ORM\Column]
    private ?float $distance_agence = null;

    #[ORM\Column]
    private ?float $nombre_habitant = null;

    #[ORM\OneToMany(mappedBy: 'commune', targetEntity: Quartier::class)]
    private Collection $quartiers;

    public function __construct()
    {
        $this->quartiers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCommune(): ?string
    {
        return $this->nom_commune;
    }

    public function setNomCommune(string $nom_commune): static
    {
        $this->nom_commune = $nom_commune;

        return $this;
    }

    public function getDistanceAgence(): ?float
    {
        return $this->distance_agence;
    }

    public function setDistanceAgence(float $distance_agence): static
    {
        $this->distance_agence = $distance_agence;

        return $this;
    }

    public function getNombreHabitant(): ?float
    {
        return $this->nombre_habitant;
    }

    public function setNombreHabitant(float $nombre_habitant): static
    {
        $this->nombre_habitant = $nombre_habitant;

        return $this;
    }

    /**
     * @return Collection<int, Quartier>
     */
    public function getQuartiers(): Collection
    {
        return $this->quartiers;
    }

    public function addQuartier(Quartier $quartier): static
    {
        if (!$this->quartiers->contains($quartier)) {
            $this->quartiers->add($quartier);
            $quartier->setCommune($this);
        }

        return $this;
    }

    public function removeQuartier(Quartier $quartier): static
    {
        if ($this->quartiers->removeElement($quartier)) {
            // set the owning side to null (unless already changed)
            if ($quartier->getCommune() === $this) {
                $quartier->setCommune(null);
            }
        }

        return $this;
    }
}

src/Form/CommuneType.php
<?php

namespace App\Form;

use App\Entity\Commune;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommuneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_commune', TextType::class, [
                'attr' => [
                    'class' => 'form-control mb-3',
                    'placeholder' => 'Entrer le nom du commune',
                    'required' => true
                ]
            ])
            ->add('distance_agence', NumberType::class, [
                'attr' => [
                    'class' => 'form-control mb-3',
                    'placeholder' => 'Entrer la distance',
                    'required' => true
                ]
            ])
            ->add('nombre_habitant', NumberType::class, [
                'attr' => [
                    'class' => 'form-control mb-3',
                    'placeholder' => 'Entrer le nombre habitant',
                    'required' => true
                ]
            ])
            ->add('submit', SubmitType::class, [
                'label' => $options['is_edit'] ? 'Modifier' : 'Ajouter',
                'attr' => ['class' => 'form-control mb-3']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commune::class,
            'is_edit' => false
        ]);
    }
}

src/Controller/CommuneController.php
<?php

namespace App\Controller;

use App\Entity\Commune;
use App\Form\CommuneType;
use App\Repository\CommuneRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CommuneController extends AbstractController
{

    public function __construct
    (
        private EntityManagerInterface $em
    )
    {
        
    }

    #[Route('/', name: 'app_commune', methods:['GET'])]
    public function index(): Response
    {
        $communes = $this->em->getRepository(Commune::class)->findAll();
            return $this->render('commune/index.html.twig', [
                'communes' => $communes 
            ]);
    }

    #[Route('/insertCommune', name:'app_commune_insert', methods:['GET','POST'])]
    public function insert(Request $request): Response 
    {
        $commune = new Commune();
        $form = $this->createForm(CommuneType::class, $commune);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $this->em->persist($commune);
            $this->em->flush();

            $this->addFlash('success', 'Commune Ajouter');
            return $this->redirectToRoute('app_commune');
         }
        return $this->render('commune/insertCommune.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/{id}/communeDelete', name:'app_commune_delete', methods:['GET','POST'])]
    public function deleteCommune(Commune $commune,CommuneRepository $communeRepository):Response
    {
        //if($this->isCsrfTokenValid('delete_commune'.$commune->getId(), $request->request->get('__token'))){
            $communeRepository->remove($commune, true);
            $this->addFlash('success', 'Commune Supprimer');
        //}
        return $this->redirectToRoute('app_commune');

    }

    #[Route('/{id}/show', name:'app_commune_one', methods:['GET'])]
    public function showOne($id):Response
    {
        $entity = $this->em->getRepository(Commune::class)->findOneBy(['id' => $id]);
        if(!$entity){
            return $this->render('page404.html.twig');
        }else{
            return $this->render('commune/show.html.twig', [
                'commune' => $entity
            ]);       
        }
    }

    #[Route('/{id}/edit', name:'app_commune_edit', methods:['GET', 'POST'])]
    public function editCommune(Request $request, Commune $commune)
    {
        $form = $this->createForm(CommuneType::class, $commune, ['is_edit'=> true]);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $this->em->persist($commune);
            $this->em->flush();

            $this->addFlash('success', 'Commune Modifier');
            return $this->redirectToRoute('app_commune');
        }
        //     $this->addFlash('error', 'Commune not update');
        //     return $this->redirectToRoute('app_commune_edit');
        // }
        return $this->render('commune/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

templates/commune/edit.html.twig
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %} {% endblock %}</title>
        {% block stylesheets %}
            
        {% endblock %}

        {% block javascript %}
            
        {% endblock %}

    </head>
    <body>
        {% block body %}            
            <div class="container">
            {% apply upper %}
                Update Commune
            {% endapply %}            
                <div class="form">
                    <div class="form-group">
                        {{form_start(form)}}
                            {{form_widget(form)}}
                        {{form_end(form)}}
                    </div>
                </div>
            </div>
        {% endblock %}
    </body>
</html>

templates/commune/index.html.twig
        {% extends 'base.html.twig' %}
        {% block title %}
            Mes communes
        {% endblock %}
        {% block body %}
        

        <div class="container">
            {% apply upper %}
                Commune
            {% endapply %}

            <div class="text-end">
                <a class="btn btn-primary" href={{path('app_commune_insert')}}>Insert</a>
            </div>
            <div class="table table-responsive mt-3">
                <table class="table table-bordered">
                    <thead>
                        <tr scope="col">
                            <td scope="col">Nom du commune</td>
                            <td scope="col">Distance de l'agence</td>
                            <td scope="col">Nombre d'habitant</td>
                            <td scope="col">Action</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for commune in communes %}
                        <tr>
                                <td>{{ commune.nomCommune }}</td>                                    
                                <td>{{ commune.distanceAgence }}</td>                                    
                                <td>{{ commune.nombreHabitant }}</td>
                                <td>
                                    {# <input type="hidden" name="_token" value="{{ csrf_token('delete_commune' ~ commune.id) }}"> #}
                                    <a class="btn btn-danger" href={{  path('app_commune_delete', {'id': commune.id})  }}>Delete</a>
                                    <a class="btn btn-secondary" href={{  path('app_commune_edit', {'id': commune.id})  }}>Edit</a>
                                </td>                                    
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>            

            
        {% endblock %}
   

templates/commune/insertCommune.html.twig
        {% extends 'base.html.twig' %}
        {% block title %}Insert Commune {% endblock %}

        {% block body %}            
            
            <div class="container">
            {# {% apply upper %} #}
                <h1 class="mt-3" style="color:#8a9e00;">Insert Commune</h1>
            {# {% endapply %}             #}
                <div class="form">
                    <div class="form-group">
                        {{form_start(form)}}
                            {{form_widget(form)}}
                        {{form_end(form)}}
                    </div>
                </div>
            </div>
        {% endblock %}
    

templates/commune/show.html.twig
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %} {% endblock %}</title>
        {% block stylesheets %}
            
        {% endblock %}

        {% block javascript %}
            
        {% endblock %}

    </head>
    <body>
        {% block body %}            
            {% apply upper %}
                Information
            {% endapply %}
            
            <div class="form">
                <div class="form-group">
                    <div class="form-control">
                        <label>Nom:</label>
                        <p><em>{{commune.nomCommune}}</em></p>
                    </div>
                </div>
            </div>
            <div class="form">
                <div class="form-group">
                    <div class="form-control">
                        <label>Distance</label>
                        <p><em>{{commune.distanceAgence}}</em></p>
                    </div>
                </div>
            </div>
            <div class="form">
                <div class="form-group">
                    <div class="form-control">
                        <label>Habitant:</label>
                        <p><em>{{commune.nombreHabitant}}</em></p>
                    </div>
                </div>
            </div>
        {% endblock %}
    </body>
</html>