src/Entity/Commune.php
<?php

namespace App\Entity;

use App\Repository\CommuneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommuneRepository::class)]
class Commune
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_commune = null;

    #[ORM\Column]
    private ?float $distance_agence = null;

    #[ORM\Column]
    private ?float $nombre_habitant = null;

    #[ORM\OneToMany(mappedBy: 'commune', targetEntity: Quartier::class)]
    private Collection $quartiers;

    public function __construct()
    {
        $this->quartiers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCommune(): ?string
    {
        return $this->nom_commune;
    }

    public function setNomCommune(string $nom_commune): static
    {
        $this->nom_commune = $nom_commune;

        return $this;
    }

    public function getDistanceAgence(): ?float
    {
        return $this->distance_agence;
    }

    public function setDistanceAgence(float $distance_agence): static
    {
        $this->distance_agence = $distance_agence;

        return $this;
    }

    public function getNombreHabitant(): ?float
    {
        return $this->nombre_habitant;
    }

    public function setNombreHabitant(float $nombre_habitant): static
    {
        $this->nombre_habitant = $nombre_habitant;

        return $this;
    }

    /**
     * @return Collection<int, Quartier>
     */
    public function getQuartiers(): Collection
    {
        return $this->quartiers;
    }

    public function addQuartier(Quartier $quartier): static
    {
        if (!$this->quartiers->contains($quartier)) {
            $this->quartiers->add($quartier);
            $quartier->setCommune($this);
        }

        return $this;
    }

    public function removeQuartier(Quartier $quartier): static
    {
        if ($this->quartiers->removeElement($quartier)) {
            // set the owning side to null (unless already changed)
            if ($quartier->getCommune() === $this) {
                $quartier->setCommune(null);
            }
        }

        return $this;
    }
}

src/Entity/Quartier.php
<?php

namespace App\Entity;

use App\Repository\QuartierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: QuartierRepository::class)]
class Quartier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'quartiers')]
    private ?Commune $commune = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle_quartier = null;

    #[ORM\OneToMany(mappedBy: 'quartier', targetEntity: Logement::class)]
    private Collection $logements;

    public function __construct()
    {
        $this->logements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommune(): ?Commune
    {
        return $this->commune;
    }

    public function setCommune(?Commune $commune): static
    {
        $this->commune = $commune;

        return $this;
    }

    public function getLibelleQuartier(): ?string
    {
        return $this->libelle_quartier;
    }

    public function setLibelleQuartier(string $libelle_quartier): static
    {
        $this->libelle_quartier = $libelle_quartier;

        return $this;
    }

    /**
     * @return Collection<int, Logement>
     */
    public function getLogements(): Collection
    {
        return $this->logements;
    }

    public function addLogement(Logement $logement): static
    {
        if (!$this->logements->contains($logement)) {
            $this->logements->add($logement);
            $logement->setQuartier($this);
        }

        return $this;
    }

    public function removeLogement(Logement $logement): static
    {
        if ($this->logements->removeElement($logement)) {
            // set the owning side to null (unless already changed)
            if ($logement->getQuartier() === $this) {
                $logement->setQuartier(null);
            }
        }

        return $this;
    }
}

src/Controller/QuartierController.php
<?php 

namespace App\Controller;

use App\Entity\Quartier;
use App\Form\QuartierFormType;
use App\Repository\QuartierRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class QuartierController extends AbstractController{
    
    public function __construct(private EntityManagerInterface $em)
    {
        
    }

    #[Route('/listQuartier', name:'app_list_quartier', methods:['GET'])]
    public function list():Response
    {
        $quartiers = $this->em->getRepository(Quartier::class)->findAll();
        return $this->render('quartier/list.html.twig', [
            'quartiers' => $quartiers
        ]);
    }

    #[Route('/insertQuartier', name:'app_insert_quartier', methods:['GET', 'POST'])]
    public function insertQuartier(Request $request):Response
    {
        $quartier = new Quartier();
        $form = $this->createForm(QuartierFormType::class,$quartier);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $this->em->persist($quartier);
            $this->em->flush();
            $this->addFlash('success', 'Quartier Ajouter');
            return $this->redirectToRoute('app_list_quartier');
        }
        return $this->render('quartier/insertQuartier.html.twig',[
            'form' => $form
        ]);
    }

    #[Route('/showQuariter/{id}', name:'app_show_quartier', methods:['GET'])]
    public function showQuartier($id):Response
    {
        $quartier = $this->em->getRepository(Quartier::class)->findOneBy(['id' => $id]);
        if(!$quartier){
            return $this->render('page404.html.twig');
        }

        return $quartier;
    }

    #[Route('deleteQuartier/{id}', name:'app_delete_quartier', methods:['GET'])]
    public function deleteQuartier(Quartier $quartier, QuartierRepository $quartierRepository):Response
    {
        $quartierRepository->remove($quartier, true);
        $this->addFlash('success', 'Commune Supprimer');
        return $this->redirectToRoute('app_list_quartier');
    }

    #[Route('editQuartier/{id}', name:'app_edit_quartier', methods:['GET','POST'])]
    public function editQuartier(Request $request, Quartier $quartier):Response
    {
        $form = $this->createForm(QuartierFormType::class, $quartier, ['is_edit' => true]);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $this->em->persist($quartier);
            $this->em->flush();
            $this->addFlash('success', 'Quartier Modifier');
            return $this->redirectToRoute('app_list_quartier');
        }
        return $this->render('quartier/editQuartier.html.twig',[
            'form' => $form
        ]);
    }


}

templates/quartier/editQuartier.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    Modifier Quartier    
{% endblock %}

{% block body %}
    <div class="container">
        {% apply upper %}
            Modification d'un cartier
        {% endapply %}
        <div class="form">
            <div class="form-group">
                {{form_start(form)}}
                    {{form_widget(form)}}
                {{form_end(form)}}
            </div>
        </div>
    </div>
    
{% endblock %}

templates/quartier/insertQuartier.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    Insert Quartier    
{% endblock %}

{% block body %}
    <div class="container">
        {% apply upper %}
            Insert Quartier
        {% endapply %}
        <div class="form">
            <div class="form-group">
                {{form_start(form)}}
                    {{form_widget(form)}}
                {{form_end(form)}}
            </div>
        </div>
    </div>
    
{% endblock %}

templates/quartier/list.html.twig
{% extends 'base.html.twig' %}
        {% block title %}
            Mes quartiers
        {% endblock %}
        {% block body %}
        

        <div class="container">
            {% apply upper %}
                Quartiers
            {% endapply %}

            <div class="text-end">
                <a class="btn btn-primary" href={{path('app_insert_quartier')}}>Insert</a>
            </div>
            <div class="table table-responsive mt-3">
                <table class="table table-bordered">
                    <thead>
                        <tr scope="col">
                            <td scope="col">Nom du commune</td>
                            <td scope="col">Quartier de</td>
                            <td scope="col">Action</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for quartier in quartiers %}
                        <tr>
                                <td>{{ quartier.commune.nomCommune }}</td>                                    
                                <td>{{ quartier.libelleQuartier }}</td>                                    
                                <td>
                                    {# <input type="hidden" name="_token" value="{{ csrf_token('delete_commune' ~ commune.id) }}"> #}
                                    <a class="btn btn-danger" href={{path('app_delete_quartier', {'id': quartier.id})}}>Delete</a>
                                    <a class="btn btn-secondary" href={{path('app_edit_quartier', {'id': quartier.id})}}>Edit</a>
                                </td>                                    
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>            

            
        {% endblock %}